# Generated by Django 5.2.8 on 2025-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_timestamp_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown event type"),
                    ("created", "Create Event"),
                    ("sync", "Sync Event"),
                    ("viewed", "View Event"),
                    ("saved", "Save or Update Event"),
                ],
                default="viewed",
                max_length=40,
            ),
        ),
    ]
